In [29]:
import numpy as np
import math
import numpy as np

arrayex = [[2, 1, 2, 0, 1],
           [0, 2, 1, 1, 2],
           [0, 1, 2, 2, 0],
           [2, 1, 2, 0, 2],
           [1, 2, 1, 0, 1]]

np_arrayex = np.array(arrayex)

print(np_arrayex)




[[2 1 2 0 1]
 [0 2 1 1 2]
 [0 1 2 2 0]
 [2 1 2 0 2]
 [1 2 1 0 1]]


In [30]:
def C10(array , num):
    for i in range(0, len(array)):
        for j in range(0, len(array[i])-1):
            cd[array[i][j]][array[i][j+1]] += 1

num = 3
cd = np.zeros((num, num), dtype=np.uint8)

C10(arrayex, num)
print("Cd :")
print(cd)
sum = np.sum(cd)
print("sum",sum)
nd = cd/sum
print("nd :")
print(nd)

Ndi = np.sum(nd, axis=1)
print("Ndi :" , Ndi)
Ndj = np.sum(nd, axis=0)
print("Ndj :" , Ndj)


x2d = 0
for i in range(0, len(nd)):
    for j in range(0, len(nd[i])):
        x2d = x2d + pow(nd[i][j], 2)/(Ndi[i]*Ndj[j]) 
        # print("x2 : ", x2)
x2d = x2d - 1
print("x2d : ", x2d)

Cd :
[[0 3 2]
 [1 1 5]
 [3 4 1]]
sum 20
nd :
[[0.   0.15 0.1 ]
 [0.05 0.05 0.25]
 [0.15 0.2  0.05]]
Ndi : [0.25 0.35 0.4 ]
Ndj : [0.2 0.4 0.4]
x2d :  0.3718750000000002


In [31]:
import math

energy = 0
entropy = 0
contrast = 0
Homogeneity = 0
Corralation = 0
for i in range(0, len(nd)):
    for j in range(0, len(nd[i])):

        energy = energy + pow(nd[i][j], 2)

        if nd[i][j] > 0:
            entropy += nd[i][j] * math.log(nd[i][j])
        else:
            entropy += 0

        contrast = contrast + (i-j)*(i-j)*nd[i][j]

        Homogeneity = Homogeneity + nd[i][j]/(1+abs(i-j))

        

print("energy : ", energy)
print("entropy : ", -1*entropy)
print("contrast : ", contrast)
print("Homogeneity : ", Homogeneity)



energy :  0.165
entropy :  1.9172155185650601
contrast :  1.6500000000000001
Homogeneity :  0.5083333333333334
